server:
  port: 9097

spring:
  application:
    name: job-match-service
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:resumade_job_match}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USER:Z4RY}
    password: ${DB_PASSWORD:ABmysql14}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://127.0.0.1:8761/eureka}
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET:GC0AnL4/4Xawm3eHaNxFgS6rt2tM2JoL37SK9VHtdtpXXavwOKvC+ai9FmwnCD36}

jooble:
  api-key: ${JOOBLE_API_KEY:074a6a76-e941-4810-ade7-5586cac14e21}

ai:
  gemini:
    api-key: ${GEMINI_API_KEY:AIzaSyBjuS0I1Tumf9pzJAgOAAd_7kelNDo1Cpo}
    model: gemini-2.5-flash

services:
  resume-url: http://resume-service

management:
  endpoints:
    web:
      exposure:
        include: health,info
